fix: use IP addresses for inter-pod communication in lightweight deployment
Fixed psycopg2.OperationalError database connection issue.

Problem:
```
psycopg2.OperationalError: could not translate host name
"hookprobe-database-postgres.dns.podman" to address:
Name or service not known
```

Root Cause:
- Django container was using Podman DNS format (.dns.podman)
- Containers were in separate pods on different networks:
  * POD_WEB on NETWORK_WEB (10.250.1.0/24)
  * POD_DATABASE on NETWORK_DATABASE (10.250.2.0/24)
  * POD_CACHE on NETWORK_CACHE (10.250.3.0/24)
  * POD_IAM on NETWORK_IAM (10.250.4.0/24)
- Podman DNS doesn't work across different networks
- Django couldn't resolve database hostname

Solution:
1. Changed environment variables to use IP addresses instead of DNS:
   - POSTGRES_HOST: $IP_DATABASE_POSTGRES (10.250.2.10)
   - REDIS_HOST: $IP_CACHE_REDIS (10.250.3.10)
   - LOGTO_ENDPOINT: http://$IP_IAM_LOGTO:$PORT_LOGTO (10.250.4.10:3001)

2. Added Django container to additional networks:
   - --network="$NETWORK_DATABASE" (to reach PostgreSQL)
   - --network="$NETWORK_CACHE" (to reach Redis)
   - --network="$NETWORK_IAM" (to reach Logto)

Benefits:
- Direct IP-based communication across networks
- No DNS resolution required
- More reliable for lightweight deployments
- Django can now connect to all required services

Files Modified:
- install/testing/lightweight-setup.sh:474-481

Testing: Raspberry Pi 4B lightweight deployment